### ISSUE TITLE
accept stdin & write to stdout

### ISSUE THREAD

**Issue by gregwebs** [btford/ngmin#13]
This can be triggered with a flag, perhaps called --stdio

**Comment by btford** [comment]
I think it should read from/write to stdio if no filenames args are provided.

**Comment by gregwebs** [comment]
sounds good.

**Comment by btford** [comment]
Landed in 3f54287ef1ec65dc8abdf493f8575f801fabb6ce, and now available in `v0.3.4`.

Thanks!

**Comment by gregwebs** [comment]
awesome, thanks, I will try out when I get back from vacation.
