### ISSUE TITLE
Grunt plugin

### ISSUE THREAD

**Issue by geddski** [btford/ngmin#15]
ngmin is looking really great, I'd like to start using it in my grunt build. Do you have plans for a Grunt plugin? I'm happy to write it too if you'd like.

**Comment by geddski** [comment]
So I made one: https://github.com/geddesign/grunt-ngmin
Then I saw you already had. Blast.

**Comment by btford** [comment]
Sorry for not getting back to you sooner. My grunt task might not be the
most awesome; PRs and input are welcome.

**Comment by geddski** [comment]
No problem, collaboration FTW. Sent some things in https://github.com/btford/grunt-ngmin/pull/3
