### ISSUE TITLE
Needs a tag line

### ISSUE THREAD

**Issue by dylang** [btford/ngmin#17]
something like 

_**Injects the dependency injection strings so you don't have to!**_

or

_**No more ugly string arrays**_

or something else....

Basically one line saying how this is different than just using Uglify.

**Comment by btford** [comment]
I am having a hard time writing a good one liner that is easy to digest and explains what this actually does. So instead, I added this: https://github.com/btford/ngmin/blob/master/README.md#tldr

If that doesn't seem good enough, we can re-open this issue.
