### ISSUE TITLE
Sprockets/Rails Support

### ISSUE THREAD

**Issue by seanpdoyle** [btford/ngmin#20]
It would be really nice to `DRY` up annotations in my Rails app. Any plans on a port that adds this to the Sprockets/Rails asset pipeline?

I'm pretty new to using Rails, especially the asset pipeline. Not sure how familiar you are with the ins and outs yourself, but do you know if there is currently a way to do Rails asset pipeline / `grunt` integration?

**Comment by btford** [comment]
I regularly don't use Rails, so I'm a bit hesitant to maintain something like this myself.

I'd imagine there is some way to spawn/run a command from the asset pipeline, with which you could use the `ngmin` CLI.

**Comment by btford** [comment]
I'm going to close this, because I think it's outside the scope of ngmin. If someone wants writes up an asset pipeline plugin/gem that uses this as a dependency, lemme know and I'd be happy to link it here.

**Comment by btford** [comment]
Okay there seems to be substantial interest for this. I'm going to leave this open to the community, but if you guys want I could throw up a [bountysource](https://www.bountysource.com) thing for it.

**Comment by BinaryMuse** [comment]
@jasonm and I just published `ngmin-rails` to integrate ngmin with the Rails asset pipeline. It uses ExecJS and thus doesn't require Node.js to be installed, and we build ngmin into a self-contained unit using [Browserify](https://github.com/substack/node-browserify).

RubyGems page: http://rubygems.org/gems/ngmin-rails

**Comment by btford** [comment]
Added a link to the readme. Thanks again @BinaryMuse!
