### ISSUE TITLE
Support anonymous factory

### ISSUE THREAD

**Issue by terasaka2k** [btford/ngmin#22]
It would be nice to support anonymous factories.
Currently implicit injections like below fails because it is not converted to explicit ones.

``` javascript
$httpProvider.interceptors.push(function($someService) { ... })
```

**Comment by btford** [comment]
This seems like a bit more work than it's worth, but I'm willing to consider it for a future release.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
