### ISSUE TITLE
Issue on Windows

### ISSUE THREAD

**Issue by fitzchak** [btford/ngmin#28]
I get the following exception, using ngmin 0.0.2:

```
Running "ngmin:dist" (ngmin) task
ngminifying dist/scripts/scripts.js, dist/scripts/templates.js
Warning: Line 576: Invalid regular expression Use --force to continue.

Aborted due to warnings.
```

**Comment by btford** [comment]
It looks like you're using `grunt-ngmin`. Please update, and try again. If there are still issues, file an issue on [`grunt-ngmin`](https://github.com/btford/grunt-ngmin) after running with `--stack` to get a stack trace. Thanks!
