### ISSUE TITLE
Annotations are not added in modules with a constant definition at first place

### ISSUE THREAD

**Issue by mlegenhausen** [btford/ngmin#32]
Working:

```
angular.module('foo', [])

.service('someService', function(someDep) {
  ...
})

.constant('someConstant', {
  ...
})

;
```

Not working:

```
angular.module('foo', [])

.constant('someConstant', {
  ...
})

.service('someService', function(someDep) {
  ...
})

;
```

In the first code example the service definition gets annotated, in the second not. This happens with the other functions like `factory`, `provider`, `run` aso too.

**Comment by ajoslin** [comment]
+1, just encountered this myself.

**Comment by BinaryMuse** [comment]
I'm not able to reproduce this on master:

```
$ cat test.js
angular.module('foo', [])

.constant('someConstant', {
  //
})

.service('someService', function(someDep) {
  //
})

;

$ ./bin/ngmin < test.js
angular.module('foo', []).constant('someConstant', {}).service('someService', [
  'someDep',
  function (someDep) {
  }
]);
;
```

**Comment by mlegenhausen** [comment]
With the latest version of ngmin the problem is fixed. I get the same result with version 0.3.6. I encountered the problem with the grunt-ngmin task. Please update the ngmin dependency.
