### ISSUE TITLE
Support minification of $httpProvider.responseInterceptors.push functions

### ISSUE THREAD

**Issue by chadly** [btford/ngmin#37]
This currently doesn't get processed correctly:

```
$httpProvider.responseInterceptors.push(function ($q, $location) {
...
});
```

This is the only spot in my code right now that I have to manually configure.

Not sure if this is related to #35 or if the fix for that will also support this.

**Comment by btford** [comment]
This is separate from #35, but also worthwhile.

**Comment by olanod** [comment]
+1

**Comment by hartror** [comment]
`Uncaught Error: Unknown provider: aProvider <- a <- $http <- userService`

Hit this error today. Was a tad bit confusing at first and took a while to track down the problem to `$httpProvider.responseInterceptors.push`.

**Comment by mikhae1** [comment]
+1

**Comment by travischoma** [comment]
+1

**Comment by ormagomy** [comment]
+1

**Comment by Cordobo** [comment]
+1

**Comment by stefan--** [comment]
```
$httpProvider.responseInterceptors.push(['$q', '$location', 
  function ($q, $location) {
  ...
  }
]);
```

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
