### ISSUE TITLE
Please add support for annotation when angular alias is used

### ISSUE THREAD

**Issue by malsup** [btford/ngmin#39]
ngmin fails to annotate when an alias variable is used for 'angular'.  I typically write my code in the following style:

```
(function(ng) {
"use strict";
var app = ng.module('app', []);
app.controller( 'ExampleCtrl', function($scope) {
    // stuff
});
})(angular);
```

If `ng.module` is replaced with `angular.module` in the above example, then it works correctly.

**Comment by btford** [comment]
This should work:

``` javascript
(function(angular) {
"use strict";
var app = angular.module('app', []);
app.controller( 'ExampleCtrl', function($scope) {
    // stuff
});
})(angular);
```

I'm not willing to make`ngmin` more complex to save a few keystrokes. If you want this feature, PRs are welcome.

**Comment by malsup** [comment]
Fair enough.
