### ISSUE TITLE
$inject Annotations for constructors

### ISSUE THREAD

**Issue by arunjitsingh** [btford/ngmin#40]
(From [here](http://docs.angularjs.org/guide/di#dinjectannotation))

Turn this:

``` js
function MyCtrl($scope, xyz) {
  //...
}
```

into this:

``` js
function MyCtrl($scope, xyz) {
  //...
}
MyCtrl['$inject'] = ['$scope', 'xyz'];
```

and the same for constructors defined as `var MyCtrl = function($scope) {...}`.

**Comment by BinaryMuse** [comment]
Oh man, I really dislike the global function version of controller declaration--I wish the AngularJS documentation didn't even mention it. (People get that mode stuck in their heads and it's harder to transition them into modules for things like services and directives.)

My feelings aside, could ngmin even detect that this function is an AngularJS controller? Aside from the tag `Ctrl` and the variable `$scope`, it looks like any other function. IIRC, it currently [looks for calls on variables declared with `angular.module`](https://github.com/btford/astral-angular-annotate/blob/ef171092d713064f06a80746a3569c71d6ccda25/signatures/simple.js#L27-29) to determine what belongs in Angular-land.

**Comment by btford** [comment]
If you care enough yo minify the app, you should also care enough not to use global controllers.

**Comment by arunjitsingh** [comment]
The closure compiler uses --angular_pass with an `@ngInject` annotation ([see comment here](https://plus.google.com/118020397223309256905/posts/VJiqHiqKU8u)).

Global controllers are relative.. The code is concatenated inside `(function(){ 'use strict'; ... })()`.

What's an alternative way of dividing code among files? A global `module = angular.module('...', [...])`, or use `angular.module('...')` everywhere, hard-coding the name of the module in every file? Is there a better way to handle the latter case?

**Comment by arunjitsingh** [comment]
I understand that the closure compiler does its own thing, but there are some advantages to having things available globally during development. Not a big requirement, but nice to have. I'd like to be able to use an alternative way (preferably one that is available during development, with or without Batarang), but I don't think it's a good idea to fix constructors to a module (maybe fine for controllers, not so for all kinds of providers).

**Comment by arunjitsingh** [comment]
I've been thinking about this, and the only place that I think I would want to define constructors globally is when I want to share services (providers) between modules. Finally, I think that shared providers should get their own module, because I think that's what modules are for.

I still don't like using the same value (the module name) in multiple files to define things.

Just thinking away.. maybe providers/controllers/etc could be registered directly with `angular`, and then attached to a module? _But what would really be the point of that?_ How will dependencies get resolved?

PS: _Next time I won't use controllers as sample code. I searched for it, and all discussions about global constructors in Angular talk about controllers, almost exclusively :) . Too hot a topic to mess with._

**Comment by btford** [comment]
> shared providers should get their own module, because I think that's what modules are for.

Yup, I think this is the way to go.

> I still don't like using the same value (the module name) in multiple files to define things.

You mean:

``` js
var foo = angular.module('whatever', []);

// another file:
foo.controller( ... );
```

versus:

``` js
angular.module('whatever', []);

// another file:
angular.module('whatever').controller( ... );
```

?

I don't see how it's any different. In the cast of refactoring, you still have to change the same amount of info. If you use the first, you likely have an additional pair of identifiers to worry about (the module alias identifier).

The second way is preferred because it avoids globals.

> PS: Next time I won't use controllers as sample code. I searched for it, and all discussions about global constructors in Angular talk about controllers, almost exclusively :) . Too hot a topic to mess with.

Doesn't matter if it's a controller or provider; the preferred method for registering things is the one that avoids globals.

**Comment by arunjit** [comment]
Either way implies that the module name is shared between files. I'd rather keep files independent of the module, and just configure the module once. I guess I think that way because I started with DI/modules using Guice.

Thanks!
