### ISSUE TITLE
Decorators not properly annotated

### ISSUE THREAD

**Issue by danielmcormond** [btford/ngmin#43]
I believe the current implementation for annotating AngularJS [decorators](http://docs.angularjs.org/api/AUTO.$provide#decorator) might be wrong.

It looks like the current decorator test in [`simple.js:112`](https://github.com/btford/ngmin/blob/master/test/simple.js#L112) isn't realistic.

For example, if you actually used this syntax in an app:

``` javascript
angular.module('myMod', [])
  .decorator('myService', function (dep) {});
```

You would get this error:

``` console
Uncaught TypeError: Object #<Object> has no method 'decorator'
```

I believe a valid decorator definition looks more like this:

``` javascript
angular.module('myMod', [])
  .config(function($provide) {
    $provide.decorator('myService', function($delegate) {});
  });
```

In this case, the `$delegate` dependency is not being correctly annotated.

Unfortunately, I don't have time to work on a PR right now. But I at least wanted to create an issue in case others experience this and are searching. :smile:

**Comment by mgcrea** [comment]
:+1: same issue here

**Comment by btford** [comment]
confirmed; this was a silly error on my part.

**Comment by marcalj** [comment]
I'm not completelly sure if this issue is related in fact $provide.factory isn't ngminfied.

``` javascript
    .config(function ($provide, $routeProvider) {
        var resolve = {
            auth: 'authResolve'
        };

        $provide.factory('authResolve', function (AuthService) {
            return AuthService.check();
        });
```

becomes:

``` javascript
.config([
  '$provide',
  '$routeProvider',
  function ($provide, $routeProvider) {
    var resolve = {
        auth: 'authResolve',
        cache: 'cacheResolve'
      };
    $provide.factory('authResolve', function (AuthService) {
      return AuthService.check();
    });
```

authResolve is not parsed correctly.

**Comment by kirill-konshin** [comment]
Still does not work:

``` js
$provide.decorator("$exceptionHandler", function($delegate, $injector, $log) {
```

is skipped...

**Comment by steve8708** [comment]
+1 on this, would be really nice!

**Comment by mike1808** [comment]
Met this issue today
+1

**Comment by eddiemonge** [comment]
Try using ng-annotate as that will replace ng-min soon
