### ISSUE TITLE
No license provided

### ISSUE THREAD

**Issue by sfried** [btford/ngmin#47]
Please include whatever software license that you desire.  We can't take advantage of this code until the author includes an appropriate license that would allow us to download and execute the code.

**Comment by BinaryMuse** [comment]
Not sure if it meets your requirements for use, but there is a license name [specified in the `package.json` file](https://github.com/btford/ngmin/blob/b9dbd0174436bb65d6ad1de840aaffcb9d023693/package.json#L6), which also causes [npmjs.org to list the license](https://npmjs.org/package/ngmin).
