### ISSUE TITLE
Support for references

### ISSUE THREAD

**Issue by jreading** [btford/ngmin#49]
I understand this is somewhat documented, but it would be nice if this worked where files are broken out:

bootstrap.js:
`var myapp = angular.module('myApp', []);`

directives.js:
`myapp.directive('myDirective', function($scope){`

Seems like a ref would be a bit more performance focused, instead of calling an angular method in each file.

**Comment by btford** [comment]
> where files are broken out

Run `ngmin` after your concat in your build process.

> Seems like a ref would be a bit more performance focused

The perf difference will be negligible.
