### ISSUE TITLE
Can you run this on a full project

### ISSUE THREAD

**Issue by isAlmogK** [btford/ngmin#5]
I wonder if I have to run this per file?

**Comment by btford** [comment]
For now, yes, you do have to run this per-file. You can first concatenate your files so you just run it once.

concat -> ngmin -> uglify/closure compiler

**Comment by isAlmogK** [comment]
Thanks, looks good but I think it needs to be part of Yeoman as soon as possible.

**Comment by btford** [comment]
Working on it. :)

**Comment by isAlmogK** [comment]
Thanks, side question do you have to build your project. Right now getting that error and I guess the questions is do we launch without doing a build at this stage. And wait for Yeoman to be fixed?
