### ISSUE TITLE
ngmin fails to annotate a declaration if it follows an annotated one

### ISSUE THREAD

**Issue by nkanand4** [btford/ngmin#50]
Annotation does not work for the controller if it follows an annotated factory.

``` javascript
angular.module('app')
  .factory('two', ['$scope', function($scope) {
    // ...
  }]).
  .controller('one', function($scope) {
    // ...
  });
```

**Comment by fuksito** [comment]
I confirm this. just got into this problem in my project. If there are mixed injection annotation in code, all the injections after the explicit syntax is used the functions with implicit injection won't be turned in to explicit form.

**Comment by facboy** [comment]
I have found this as well.  It seems the bug only happens if you chain declarations off the initial module call.  eg, as stated in the OP, this will not work:

``` javascript
angular.module('app')
  .factory('two', ['$scope', function($scope) {
    // ...
  }])
  .controller('one', function($scope) {
    // ...
  });
```

and I've found that this will not work:

``` javascript
var mod = angular.module('app')
  .factory('two', ['$scope', function($scope) {
    // ...
  }]);
mod.controller('one', function($scope) {
    // ...
  });
```

but that this will:

``` javascript
var mod = angular.module('app');
mod.factory('two', ['$scope', function($scope) {
    // ...
  }]);
mod.controller('one', function($scope) {
    // ...
  });
```

**Comment by eggers** [comment]
Does it also fail for when there is a chain where the first one in the chain doesn't require annotation? 

Because I'm seeing this fail to ngmin properly:

```
angular.module('app')
  .provider('one', function() {
    // ...
  }])
  .config(function(oneProvider) {
    // ...
  });
```

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
