### ISSUE TITLE
did not support JavaScript closure

### ISSUE THREAD

**Issue by xudejian** [btford/ngmin#52]
my code was generate by coffee with closure default
e.g:

(function() {
  'use strict';
}).call(this);

after ngmin

(function () {
  'use strict';
}.call(this));

it should be

(function () {
  'use strict';
}).call(this);

**Comment by xudejian** [comment]
(function () {
  'use strict';
}.call(this)`)`;

it should be

(function () {
  'use strict';
}`)`.call(this);

**Comment by btford** [comment]
These are equivalent.

`ngmin` parses and regenerates the source. What it generates is considered a best practice. There may be some other option you could pass to `escodegen` that preserves your syntax, which you could use with `ngmin` programmatically.
