### ISSUE TITLE
Support for ui-router resolve, onEnter and onExit

### ISSUE THREAD

**Issue by ghengeveld** [btford/ngmin#54]
Since ui-router of the angular-ui project is quickly becoming the de-facto replacement of Angular's routeProvider, it would be good to have full support for it. This means that the 'resolve', 'onEnter' and 'onExit' properties in $stateProvider.state() should be handled by ngmin. 

@see https://github.com/angular-ui/ui-router/wiki#onenter-and-onexit-callbacks

**Comment by ivangarcia2** [comment]
+1

**Comment by arebelrossi** [comment]
+1

**Comment by battika** [comment]
+1

**Comment by braco** [comment]
+1

**Comment by dylan-baskind** [comment]
+1 

Took me awhile to figure out that this was where my minified code was going bust. 

Does anyone have any stop-gap solution for converting the standard form of these functions, i.e.

``` resolve:
            # To Do...
            projectData: (someInjectable) ->
                # Return some data
```

To a minification safe form?

Apologies if this is a noob type question!

D.

**Comment by forgetaboutit** [comment]
@dylan-baskind : in our project, we're using

```
# To do ...
projectData: ["someInjectable", (someInjectable) ->
    # Return some data
]
```

**Comment by dylan-baskind** [comment]
@forgetaboutit - Cheers for that! 

Familiar syntax from the controller declarations, just didn't realise it would also apply here. Thanks for the tip.

**Comment by gbockus** [comment]
+1

**Comment by hengkiardo** [comment]
+1

**Comment by liujinxing** [comment]
+1

**Comment by leon** [comment]
+1

**Comment by towu** [comment]
+1

**Comment by 27leaves** [comment]
+1

**Comment by liujinxing** [comment]
+1

**Comment by cmcnamara87** [comment]
+1

**Comment by stto3703** [comment]
+1

**Comment by btford** [comment]
I think #61 will make this easier, so I'll work on getting this in ASAP. :)

**Comment by lufzle** [comment]
+1

**Comment by futurechan** [comment]
+1

**Comment by martijnve** [comment]
+1

**Comment by vrodriguezTecsisa** [comment]
+1

**Comment by julianpaulozzi** [comment]
+1

**Comment by jketcham** [comment]
:+1:

**Comment by inetfuture** [comment]
+1

**Comment by Urigo** [comment]
+1 :)

**Comment by mablk** [comment]
+1

**Comment by demetriusnunes** [comment]
+1

**Comment by donaldpipowitch** [comment]
Hi guys,

if you need this feature I would recommend to try [ng-annotate](https://github.com/olov/ng-annotate), which supports this in its new bleeding edge version (see [here](https://github.com/olov/ng-annotate/blob/master/tests/original.js#L144) for examples).

// cc @olov

**Comment by pensierinmusica** [comment]
+1  :)

**Comment by andycaramba** [comment]
and up again :+1:

**Comment by kikonen-fiksu** [comment]
Changes that any fixes for this are merged some day? i.e. I just hit trouble with ngmin and "ui-router" "resolve"s.

**Comment by donaldpipowitch** [comment]
Seriously, check ng-annotate. Here is a [comparison between ng-annotate and ngmin](https://github.com/olov/ng-annotate/blob/7dbcc7cdfdd196bb8c4bcec0a317474a65d35fc4/tests/ngmin-tests/ngmin-issues.txt).

**Comment by kikonen-fiksu** [comment]
Q: does it have rails assets pipeline integration?

**Comment by olov** [comment]
@donaldpipowitch That link shows which 24 open ngmin issues that just work in ng-annotate. In addition, there are 6 open ngmin issues that work in ng-annotate with a workaround. See [full annotated issue list](https://github.com/olov/ng-annotate/blob/master/tests/ngmin-tests/ngmin-issues.txt).

But Instead of just looking at that list I recommend reading the more elaborate comparison I wrote yesterday in issue #93 - The future of ngmin and ng-annotate. @kikonen-fiksu: That comparison also describes where ng-annotate is trailing ngmin, in particular not as extensive tooling integration (although Grunt, Browserify, Brunch and Gulp is there so far and more is coming). Q: "does ng-annotate have rails assets pipeline integration?" A: "not currently, but hopefully very soon". It should be a 30 minute job for a rails/ruby/gem savvy person to create it.

**Comment by kikonen-fiksu** [comment]
Thx, I may try to take peek on this assets integ.

**Comment by olov** [comment]
@kikonen this discussion does not belong is this thread so let's take it elsewhere (email/twitter/issue). FWIW ng-annotate does not require ES6 because defs, info in BUILD.md

**Comment by kikonen** [comment]
First draft: https://github.com/kikonen/ngannotate-rails

**Comment by ralyodio** [comment]
+1

**Comment by vincentjr** [comment]
+1 :D

**Comment by indianazhao** [comment]
+1

**Comment by didil** [comment]
+1

**Comment by andredublin** [comment]
+1

**Comment by turkingj** [comment]
+1

**Comment by 27leaves** [comment]
I also switched to ng-annotate about a month ago and haven't looked back.

**Comment by bdefore** [comment]
+1

**Comment by mattupstate** [comment]
Would this be a result of `ngmin` not "supporting" `ui-router`?

```
[Error] Error: [$injector:unpr] Unknown provider: aProvider <- a <- $http <- $templateFactory <- $view <- $state
http://errors.angularjs.org/1.2.19/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-%20%24http%20%3C-%20%24templateFactory%20%3C-%20%24view%20%3C-%20%24state
    (anonymous function) (app.js, line 2)
    c (app.js, line 2)
   ... lots more ...
```

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
