### ISSUE TITLE
Injector returned by angular.bootstrap is not treated

### ISSUE THREAD

**Issue by spalger** [btford/ngmin#57]
Calls to angular.bootstrap return an injector, but ngmin doesn't extract dependencies from there. I have a call to invoke chained to my bootstrap call that isn't be wrapped by ngmin.

```
angular.bootstrap(document, [])
  .invoke(function ($rootScope) {
    // this function isn't wrapped in it's dependencies by ngmin
  })
```

**Comment by ghost** [comment]
+1 I'm experiencing the same issue.

**Comment by ludoblues** [comment]
+1

**Comment by viniciusffj** [comment]
+1

**Comment by viniciusffj** [comment]
Anyone know some workaround to this situation?
Thanks

**Comment by spalger** [comment]
@viniciusffj just use the array notation until it is supported.

``` js
angular.bootstrap(document, [])
  .invoke(['$rootScope', function ($rootScope) {
    // this function isn't wrapped in it's dependencies by ngmin
  }])
```

**Comment by viniciusffj** [comment]
Thanks @spenceralger , it worked.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
