### ISSUE TITLE
Doesn't work when using a shortcut reference to the module

### ISSUE THREAD

**Issue by davej** [btford/ngmin#6]
For example:

```
var app = angular.module('app');

app.controller('TestCtrl', function($scope, $http) {
    $scope.test = 'heelo';
});
```

I'd imagine that this is a fairly common pattern it would be nice to have support for this.

**Comment by groner** [comment]
It would be good, as a fallback, to have an annotation to tell ngmin that a function should be wrapped.

```
var app = angular.module('app');

app.controller('TestCtrl', /** @ngmin-injected */ function($scope, $http) {
    $scope.test = 'heelo';
});
```

**Comment by btford** [comment]
This is by design right now, but I do plan to add this feature soon.

-1 for the annotation. I'd like to keep this simple and discourage people from doing anything too wacky when it comes to registering/using modules.

**Comment by btford** [comment]
I'm working on this feature today.

**Comment by anjo** [comment]
Too late :) See my pull request.

**Comment by mlegenhausen** [comment]
+1

**Comment by btford** [comment]
Added in 17d33a2f5d10e37549799e930e5072baa88ecf17.
