### ISSUE TITLE
minifications fails

### ISSUE THREAD

**Issue by waqasajaz** [btford/ngmin#64]
ngmin does not work if i write controller in following way:

``` javascript
 var myMod = angular.module('myMod', ['aaa','bbb']);
myMod.controller('myCtrl', function ($scope) {
  // ...
}); 
```

But If I write it like this

``` javascript
angular.module('myMod', ['aaa','bbb']);
angular.module('myMod').controller('myCtrl', function ($scope) {
  // ...
});
```

then it works

**Comment by otodockal** [comment]
I suppose, it's correct because of global variables.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
