### ISSUE TITLE
Minification not detecting controller style 

### ISSUE THREAD

**Issue by shanti2530** [btford/ngmin#71]
The controller is defined as follows:

``` javascript
var MainCtrl = function($scope, DataService) {...}
```

The controller is registered with the app module as follows:

``` javascript
angular.module('myApp').controller('mainCtrl', MainCtrl);
```

ngmin does not work if I write the controller and register it this way.

**Comment by gabegorelick** [comment]
:+1:  I just got bit by this.

**Comment by btford** [comment]
Please [read the readme](https://github.com/btford/ngmin#conventions).

Unless you have a compelling reason for this style of code, I'm not interested in adding this feature.
