### ISSUE TITLE
Requirejs + Angularjs issue

### ISSUE THREAD

**Issue by duperran** [btford/ngmin#72]
Hello 

I try to use ngmin on the following kind of code but nothing happens

define(['./module'], function(controllers) {
  'use strict';

  controllers.controller('SampleController', function($scope, $location, $rootScope, $timeout, $compile) {   

  });  
});

**Comment by gunta** [comment]
+1

**Comment by btford** [comment]
It's impossible for `ngmin` to statically infer that `controllers` refers to an angular module here.
