### ISSUE TITLE
Support minification of ngAnimate

### ISSUE THREAD

**Issue by d-oliveros** [btford/ngmin#73]
It would be nice to see the .animation()'s supported as well.

**Comment by btford** [comment]
:+1:

**Comment by raDiesle** [comment]
Lol, critical ! Pls fix

**Comment by btford** [comment]
Lol

**Comment by i8ramin** [comment]
Yes, please.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
