### ISSUE TITLE
ngmin reformats code, e.g. comments

### ISSUE THREAD

**Issue by raDiesle** [btford/ngmin#76]
Hi,

for grunt-replace I used  var config = "default";// REGEX_MATCHER
but ngmin will break myregex, because it will result in:
var config = "default";
// REGEX_MATCHER

ngmin should not reformat code, I think.

**Comment by btford** [comment]
This is a duplicate of #60. Please check the existing issues and PRs before posting next time. Thanks!

**Comment by seriema** [comment]
This isn't a duplicate? This says the comments gets moved, not _re_moved.
