### ISSUE TITLE
module.run not being annotated

### ISSUE THREAD

**Issue by scottnewman** [btford/ngmin#78]
The run() fails to get annotated.  If I omit the service definition it will annotate run fine.  And if myFunction was inline instead of global it would also annotate run fine.

``` javascript
function myFunction() {}
angular.module('some-module')
.service("StartingPage", myFunction)
.run(function($rootScope) {
});
```

**Comment by scamden** [comment]
+1 i'm also seeing this issue

**Comment by abulte** [comment]
+1

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
