### ISSUE TITLE
Support minification of module providers

### ISSUE THREAD

**Issue by galkinrost** [btford/ngmin#79]
`angular.module('App', [], function ($provide, $routeProvider, $httpProvider) {`

Not annotate now

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
