### ISSUE TITLE
support "this" infront of angular.module

### ISSUE THREAD

**Issue by jandob** [btford/ngmin#80]
```
this.angular.module('app', []).controller('ctrl', function($scope, SomeService) {
    return $scope.user = User;
})
```

is not annotated

**Comment by btford** [comment]
Please read the readme.

> `ngmin` does not currently attempt to be fully generalized, and might not work if you're too clever. If you follow these conventions, which are the same as what the AngularJS Yeoman generator defaults, you should be fine.
