### ISSUE TITLE
Support injector().invoke

### ISSUE THREAD

**Issue by fitzchak** [btford/ngmin#81]
```
    window.opener.angular.element(window.opener.document).injector().invoke(function(accessTokenHolder: AccessTokenHolderService) {
        accessTokenHolder.AccessToken = accessToken;
      });
```

**Comment by rpocklin** [comment]
@btford Is this an issue with ngmin or the way the 3rd party libraries are written?  Any feedback would be great.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
