### ISSUE TITLE
Support minification of modal controller

### ISSUE THREAD

**Issue by gcharpentier** [btford/ngmin#83]
Injection's of modal controller like the example of angular-ui aren't supported...

**Comment by rpocklin** [comment]
+1 See https://github.com/btford/ngmin/issues/57 for more information
Is this planned?  Seems a few issues have been raised on this topic: #81

**Comment by ludoblues** [comment]
+1, i meet the same issue.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
