### ISSUE TITLE
Support services as function references

### ISSUE THREAD

**Issue by roryf** [btford/ngmin#84]
Like a lot of the angular core, I tend to write controllers something like this:

``` javascript
function MyController($scope) { /* ... */ }

angular.module('MyApp').controller('MyController', MyController);
```

I didn't really understand the AST code very well, so don't know if this is possible.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
