### ISSUE TITLE
Inclusion in grunt-contrib-uglify

### ISSUE THREAD

**Issue by Francisc** [btford/ngmin#86]
Hello,

I think this plugin would make a lot of sense as an option to uglifyjs.
You would get real minification and sourcemaps for free, while Angular would get an easy minification process.

What do you think?

**Comment by eddiemonge** [comment]
PR welcome. Its easier said than done.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
