### ISSUE TITLE
Not working with resolve in ngRoute.

### ISSUE THREAD

**Issue by alanquigley** [btford/ngmin#87]
Looks like an old bug, but maybe a prominent mention in the docs could save a lot of head scratching.

**Comment by mlegenhausen** [comment]
Look at #61 for a possible solution.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
