### ISSUE TITLE
Support for javascript enclosures?

### ISSUE THREAD

**Issue by thardy** [btford/ngmin#89]
I'm trying to follow better javascript patterns espoused by "the greats" like Douglas Crockford, and I found that using enclosures breaks ngmin..

<pre><code>(function(app) {
    app.controller('SomeController', function ($scope) {
    });
}(angular.module("someModule")));
</code></pre>

It never sees the controller declaration and leaves it alone.  Should this be working?

**Comment by btford** [comment]
I'm not keen on this. I don't think this pattern buys you anything. 

Try ngmin with `--dynamic`.

**Comment by eddiemonge** [comment]
You can get the same enclosures doing it this way:

``` js
(function(angular) {
    angular.module("someModule").controller('SomeController', function ($scope) {
    });
}(window.angular);
```

but really the enclosure could/should(?) be added by your build system after concatenating your code

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
