### ISSUE TITLE
ngmin 30x is slower than ngAnnotate

### ISSUE THREAD

**Issue by capaj** [btford/ngmin#91]
I just replaced ngmin(grunt-ngmin@0.0.2) on a fairly big project with ng-annotate(grunt-ng-annotate@0.0.7). 
We need to annotate 6 concatenated js files that which have 2.8 MB. Ngmin took 30 seconds on my hardware to run, whereas with the same options ng-annotate took only 913ms.

This project has 10 times more stars-I don't expect it to be 10 times faster, but at least it should be on the same level of performance with a competing much less known project.

Unfortunately I cannot provide you my sources, but I suspect this performance is normal and not caused by some specific problem in my code.

**Comment by brettstack** [comment]
It's by far the slowest point in my gulpfile also. :(

**Comment by twhitbeck** [comment]
My experience also. I had at _least_ a 30x speedup with ng-annotate. I think olov mentioned that ngmin is trying to be smarter by checking that calls to `controller()` and such are being called on an actual module. Maybe it's this checks that are slowing ngmin down.
I have no experience profiling in node, but I'd love to help tackles these performance issues.

**Comment by olov** [comment]
ng-annotate is very fast for a number of reasons - there's a bit more info in issue #93. BTW @capaj feel free to re-run the performance test using ng-annotate 0.9, hopefully getting you down to 800'ish ms.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
