### ISSUE TITLE
Unexpected token ILLEGAL Use --force to continue

### ISSUE THREAD

**Issue by ksrdhilip** [btford/ngmin#95]
If I use of this line(#!/usr/bin/env node;) in my javascript file and try converting the JS file into minified file using ngmin, I'm getting the following error.

"Unexpected token ILLEGAL Use --force to continue."

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
