### ISSUE TITLE
Make it works with Browserify module structure

### ISSUE THREAD

**Issue by jgoux** [btford/ngmin#96]
Hi,
firstly, thanks for this awesome tool ! :D
I'm trying to integrate Browserify in my development workflow. It works very well.
Now it's the time to automate some tasks with gulp and ngmin, and I have an issue with the minification one.
I structure my code exactly the same way from here : http://benclinkinbeard.com/talks/2014/ng-conf/ (slides 19 to 23)

The problem is that ngmin isn't working with this kind of structure, something like this isn't parsed properly : 

``` javascript
// modules/app/frontend/login/login-index.js
'use strict';

module.exports = function($scope) {
        $scope.name = 'guest';
    };
```

The previous controller is called from here : 

``` javascript
// modules/app/frontend/login/index.js
'use strict';

module.exports = angular.module('app.frontend.login', [])
    .config(function($stateProvider) {
        $stateProvider.state('login', {
            url: '/login',
            templateUrl: '/frontend/login/login-index.html',
            controller: 'LoginCtrl'
        });
    })
    .controller('LoginCtrl', require('./login-index'));
```

Is there a solution to make ngmin understand this kind of line ?

``` javascript
.controller('LoginCtrl', require('./login-index'));
```

Maybe I'm making something wrong. ^^'

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
