### ISSUE TITLE
Issue with routeProvider when resolve option

### ISSUE THREAD

**Issue by benknoll** [btford/ngmin#98]
I'm having issues with the resolve option for a route:

```
.when('/system/:systemIndex', {
    templateUrl: 'systems/views/system.html',
    controller: 'SystemCtrl',
    reloadOnSearch: false,
    resolve: {
        system: function ($route, CasProcessingIndex) {
            return CasProcessingIndex.withIndexName($route.current.params.systemIndex);
        }
    }
})
```

I had to manually add the annotations for the function which resolves 'system' (and all similar examples) in order to prevent runtime provider errors after minification.

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
